# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.17-alpine AS build

WORKDIR /app
ENV GOPROXY=https://goproxy.cn,direct
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY *.go ./
RUN go build -o /go-http

##
## Deploy
FROM alpine
WORKDIR /
COPY --from=build /go-http /go-http
ENV HTTP_PORT=8090
EXPOSE $HTTP_PORT
USER nonroot:nonroot
ENTRYPOINT ["/go-http"]
